INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_1', 'UBICACION_1');
INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_2', 'UBICACION_2');
INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_3', 'UBICACION_3');
INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_4', 'UBICACION_4');
INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_5', 'UBICACION_5');
INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_6', 'UBICACION_6');
INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_7', 'UBICACION_7');
INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_8', 'UBICACION_8');
INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_9', 'UBICACION_9');
INSERT INTO almacen (nombre, ubicacion) VALUES('ALMACEN_10', 'UBICACION_10');

# Producto

insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_84',21);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_98',92);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_65',46);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_69',45);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_5',57);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_95',73);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_93',58);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_57',64);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_89',18);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_51',45);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_81',87);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_92',97);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_95',96);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_91',39);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_56',98);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_76',81);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_88',94);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_96',95);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_94',64);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_84',14);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_79',40);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_89',24);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_87',22);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_31',22);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_64',47);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_84',23);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_11',1);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_12',65);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_10',94);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_96',4);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_38',22);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_58',63);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_84',37);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_51',75);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_2',64);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_32',57);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_51',94);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_23',44);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_32',21);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_70',54);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_24',100);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_47',5);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_55',3);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_73',31);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_80',46);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_62',44);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_1',33);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_76',31);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_11',9);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_91',31);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_7',1);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_93',34);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_58',58);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_88',34);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_62',14);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_81',59);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_37',83);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_100',80);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_5',100);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_93',76);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_21',53);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_24',4);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_42',68);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_69',47);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_38',90);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_86',57);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_59',23);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_9',91);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_90',74);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_38',65);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_53',93);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_63',48);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_90',91);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_13',77);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_60',13);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_11',8);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_23',32);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_75',3);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_49',35);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_68',50);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_10',40);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_91',9);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_15',61);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_99',14);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_14',78);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_18',48);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_42',70);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_87',66);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_99',25);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_7',97);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_57',36);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_5',82);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_88',62);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_77',1);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_1',66);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_37',79);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_89',30);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_95',87);
insert into producto (nombre, precio_unitario) VALUES('PRODUCTO_22',84);

#Producto Almacen
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 3, 20);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 10);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 30);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 3, 40);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 6, 90);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 7, 80);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 70);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 50);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 60);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 2, 100);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 20);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 10);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 30);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 40);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 90);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 80);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 70);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 50);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 60);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 100);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 3, 22);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 4, 12);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 32);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 3, 42);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 6, 92);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 7, 82);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 72);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 52);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 62);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 2, 2);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 22);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 12);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 32);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 42);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 92);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 82);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 72);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 52);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 62);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 2);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 3, 21);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 11);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 31);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 3, 41);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 6, 91);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 7, 81);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 71);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 51);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 61);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 2, 1);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 21);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 11);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 31);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 41);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 91);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 81);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 71);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 51);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 61);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 1);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 3, 23);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 13);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 33);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 3, 43);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 6, 93);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 7, 83);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 73);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 53);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 63);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 2, 3);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 23);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 13);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 33);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 43);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 93);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 83);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 73);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 53);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 63);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 3);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 3, 24);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 14);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 34);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 3, 44);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 6, 94);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 7, 84);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 74);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 54);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 64);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 2, 4);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 24);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 14);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 34);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 44);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 94);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 84);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 74);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 54);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 64);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 4);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 3, 25);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 15);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 35);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 3, 45);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 6, 95);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 7, 85);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 75);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 55);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 65);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 2, 5);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 25);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 15);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 35);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 45);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 95);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 85);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 75);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 55);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 65);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 5);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 3, 26);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 16);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 36);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 3, 46);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 6, 96);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 7, 86);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 76);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 56);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 66);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 2, 6);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 26);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 16);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 36);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 46);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 96);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 86);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 76);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 56);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 66);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 6);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 3, 27);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 17);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 37);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 3, 47);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 6, 97);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 7, 87);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 77);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 57);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 67);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 2, 7);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 27);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 17);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 37);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 47);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 97);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 87);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 77);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 57);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 67);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 7);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 3, 28);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 18);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 38);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 3, 48);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 6, 98);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 7, 88);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 78);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 58);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 68);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 2, 8);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 28);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 18);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 38);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 48);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 98);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 88);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 78);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 58);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 68);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 8);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 3, 29);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 19);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(5, 1, 39);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 3, 49);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 6, 99);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 7, 89);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 5, 79);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 10, 59);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 9, 69);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(10, 2, 9);

INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 2, 29);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 9, 19);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(7, 10, 39);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(2, 6, 49);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(9, 7, 99);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(4, 5, 89);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(3, 4, 79);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(1, 1, 59);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(6, 3, 69);
INSERT INTO producto_almacen (stock, almacen_id, producto_id) VALUES(8, 8, 9);

#Ventas


insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,59);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,84);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,65);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,93);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,57);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,57);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,22);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,79);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,97);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,70);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,33);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,2);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2020,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,87);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,71);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2015,87);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2015,57);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,22);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,88);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,57);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,3);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,8);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,69);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,71);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2020,75);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,97);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,88);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,79);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,38);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,53);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,41);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,50);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,8);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,75);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,78);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2020,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,33);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,84);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,88);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,84);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,56);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,6);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,6);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,62);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,50);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,29);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,81);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,56);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,69);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,65);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,6);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,24);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,65);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,36);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,35);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,6);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,65);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,2);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,84);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,57);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,62);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,26);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,38);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,3);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,15);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2020,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,70);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2015,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,75);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,33);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,92);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,75);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,2);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,6);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,97);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,12);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,18);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2015,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,71);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,92);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,56);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,87);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,35);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,3);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,98);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,26);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,35);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,6);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,98);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,3);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,93);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,81);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,18);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,8);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,41);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,78);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,24);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,98);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,2);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,65);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,93);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,69);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,11);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,78);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,36);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,50);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,56);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,78);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,56);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,84);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,8);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,88);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,50);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,28);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,15);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,92);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,22);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,33);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2015,41);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,22);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,33);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,93);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,3);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,28);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,70);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,70);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,81);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,8);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,35);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,97);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,18);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,28);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,29);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,87);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,11);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,56);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,15);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,3);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,15);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,87);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,24);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,88);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,71);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,29);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,8);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,15);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,59);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2020,41);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,26);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,93);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,59);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,12);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,11);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,75);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,38);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,98);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2020,98);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,57);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,69);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,24);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,28);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,92);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,69);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,65);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,2);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,98);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,62);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,59);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,98);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,36);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,41);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,26);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,53);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,92);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2015,22);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,79);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,62);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,12);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,57);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,15);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,11);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,65);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,92);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,56);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,3);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,81);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,97);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,3);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,98);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,12);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,12);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,62);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,6);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,71);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,62);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,29);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,71);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,17);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,69);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,81);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,97);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,70);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,38);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,41);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,87);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,74);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,71);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,70);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,93);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,50);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,73);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,78);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,14);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,93);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,71);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,8);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,24);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,41);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,97);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,57);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,56);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2015,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,70);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,97);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,88);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,81);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,79);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,75);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,62);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,78);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,38);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,36);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,36);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,22);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,87);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,41);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,26);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,6);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,38);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,53);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,87);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,3);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,27);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,13);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,33);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,38);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,38);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,75);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,15);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,65);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,62);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,22);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,16);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,58);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,94);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,26);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,88);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,78);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2017,79);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,69);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,54);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,59);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2015,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,48);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,11);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,9);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,28);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,5);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,29);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2015,83);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,11);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2015,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2020,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,15);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2016,22);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,59);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,7);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2018,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,28);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,33);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,79);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,2);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,29);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,65);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,56);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2016,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2015,18);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,43);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2019,66);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2020,46);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,35);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2017,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,25);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,10);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2015,33);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,53);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,32);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,63);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2020,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,70);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,22);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,78);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2017,36);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,99);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2018,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,59);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2015,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,90);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2016,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,98);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,26);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,12);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2020,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,23);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2019,75);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,82);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,77);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,47);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2017,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2019,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2018,61);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,85);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2018,50);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,53);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2016,40);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2015,62);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2017,42);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2016,80);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2016,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2020,44);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,78);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2018,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,45);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,81);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,14);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2020,93);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2018,34);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,86);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2015,69);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2019,91);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2019,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,55);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,6);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,30);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,93);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2016,59);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2020,68);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,35);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2018,64);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,19);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2019,37);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2019,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (4,2017,49);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2016,39);
insert into ventas(almacen_id,ano_venta,producto_id) values (3,2018,89);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2016,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2020,67);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,21);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,15);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,96);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2020,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2019,72);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2017,95);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2015,31);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2019,92);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2019,51);
insert into ventas(almacen_id,ano_venta,producto_id) values (9,2020,20);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,60);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2018,29);
insert into ventas(almacen_id,ano_venta,producto_id) values (1,2015,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2020,76);
insert into ventas(almacen_id,ano_venta,producto_id) values (5,2017,1);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2017,4);
insert into ventas(almacen_id,ano_venta,producto_id) values (8,2020,52);
insert into ventas(almacen_id,ano_venta,producto_id) values (2,2016,81);
insert into ventas(almacen_id,ano_venta,producto_id) values (6,2017,69);
insert into ventas(almacen_id,ano_venta,producto_id) values (10,2018,97);
insert into ventas(almacen_id,ano_venta,producto_id) values (7,2015,22);
